production:
  adapter: postgresql
  database: development
  encoding: unicode

development:
  adapter: postgresql
  encoding: unicode
  database: development

test:
  adapter: postgresql
  database: pg_test
  encoding: unicode
